In [228]:
import pandas as pd
import sqlite3

In [205]:
df = pd.read_csv("solubilidad.csv")

In [206]:
df.head()

,año,convocatoria,ejercicio,tema,tipo_ejercicio
0,2025,Julio,Ejercicio 2B,Solubilidad,Expresión de Ks en función de s
1,2025,Julio,Ejercicio 2B,Solubilidad,Ion común - razonamiento
2,2025,Julio,Ejercicio 2B,Solubilidad,Formación de precipitado
3,2025,Julio,Ejercicio 2B,Solubilidad,Influencia del pH
4,2024,Junio,Ejercicio C2,Solubilidad,Cálculo de Ks

In [223]:
df.tipo_ejercicio.unique()

<StringArray>
[                                     'Expresión de Ks en función de s',
                                             'Ion común - razonamiento',
                                             'Formación de precipitado',
                                                    'Influencia del pH',
                                                        'Cálculo de Ks',
                                                  'Ion común - cálculo',
                                               'Cálculo de solubilidad',
                                                     'Cuestión teórica',
                                                     'Solubilidad → Ks',
                'Ks → solubilidad; Cuestión teórica; Influencia del pH',
           'Solubilidad → Ks; Influencia del pH (precipitación por pH)',
 'Cuestión teórica / V o F; Ks → solubilidad; Efecto ion común teórico',
                           'Cuestión teórica / V o F; Ks → solubilidad',
                                 'Ion común numérico; Ks → solubilidad',
                                 'Ks → solubilidad; Ion común numérico',
                'Solubilidad → Ks; Ks → solubilidad; Influencia del pH',
        'Ks → solubilidad; Efecto ion común teórico; Influencia del pH',
                                 'Solubilidad → Ks; Ion común numérico',
                           'Ks → solubilidad; Formación de precipitado',
        'Cuestión teórica; Efecto ion común teórico; Influencia del pH',
                           'Ks → solubilidad; Efecto ion común teórico',
                           'Efecto ion común teórico; Cuestión teórica',
                                                     'Ks → solubilidad',
                                                   'Ion común numérico',
                                  'Ks → solubilidad; Influencia del pH',
                                  'Solubilidad → Ks; Influencia del pH']
Length: 26, dtype: str

In [220]:
df.drop(114, axis=0, inplace=True)

In [217]:
df.ejercicio = df.ejercicio.str.replace("Ejercicio 5 Opción B", "Opción B, Ejercicio 5")

In [ ]:
cols = [f'{i}' for i in "asignatura,tema,año,convocatoria,ejercicio,tipo_ejercicio".split(",") ]
cols
# asignatura,tema,año,convocatoria,ejercicio,tipo_ejercicio

['asignatura', 'tema', 'año', 'convocatoria', 'ejercicio', 'tipo_ejercicio']

In [224]:
df["asignatura"] = "química"

In [225]:
df = df.loc[:, cols]

In [226]:
df

,asignatura,tema,año,convocatoria,ejercicio,tipo_ejercicio
0,química,Solubilidad,2025,Julio,Ejercicio 2B,Expresión de Ks en función de s
1,química,Solubilidad,2025,Julio,Ejercicio 2B,Ion común - razonamiento
2,química,Solubilidad,2025,Julio,Ejercicio 2B,Formación de precipitado
3,química,Solubilidad,2025,Julio,Ejercicio 2B,Influencia del pH
4,química,Solubilidad,2024,Junio,Ejercicio C2,Cálculo de Ks
...,...,...,...,...,...,...
130,química,Solubilidad,2011,Septiembre,"Opción A, Ejercicio 6",Ion común numérico
131,química,Solubilidad,2010,Junio,"Opción A, Ejercicio 3",Ks → solubilidad; Influencia del pH
132,química,Solubilidad,2010,Reserva 2,"Opción A, Ejercicio 3",Ks → solubilidad; Efecto ion común teórico
133,química,Solubilidad,2010,Reserva 3,"Opción B, Ejercicio 5",Solubilidad → Ks; Ion común numérico
134,química,Solubilidad,2010,Reserva 4,"Opción A, Ejercicio 6",Solubilidad → Ks; Influencia del pH

In [227]:
df.to_csv("solubilidad.csv", index = False, sep="|")

In [188]:
df.sample(10)

,asignatura,tema,año,convocatoria,ejercicio,tipo_ejercicio
164,química,Equilibrio químico,2019,Junio,"Opción A, Ejercicio 3",Principio de Le Chatelier
19,química,Equilibrio químico,2001,Reserva 4,"Opción B, Ejercicio 4",Principio de Le Chatelier (concentración / tem...
176,química,Equilibrio químico,2019,Reserva 4,"Opción A, Ejercicio 5",Cálculo de Kc y Kp
23,química,Equilibrio químico,2002,Junio,"Opción B, Ejercicio 6",Uso de alfa para calcular constantes + Cálculo...
292,química,Cinética,2025,Reserva 2,"Opción B, Ejercicio 2B",Orden de reacción
60,química,Equilibrio químico,2006,Junio,"Opción A, Ejercicio 6",Kc y Kp: cálculo numérico + presiones parciales
45,química,Equilibrio químico,2004,Reserva 1,"Opción B, Ejercicio 5",Kc y Kp: cálculo numérico
4,química,Equilibrio químico,2000,Reserva 2,"Opción B, Ejercicio 6",Equilibrio heterogéneo + Cálculo de Kp + Cálcu...
73,química,Equilibrio químico,2007,Reserva 2,"Opción A, Ejercicio 6",Equilibrio heterogéneo - presiones parciales y Kc
158,química,Cinética,2018,Reserva 2,"Opción B, Ejercicio 4",Ecuación de velocidad - verdadero o falso

In [149]:
df.drop("opcion", axis=1, inplace=True)

In [155]:
df = df.sort_values(["año", "convocatoria"]).reset_index(drop=True)

In [156]:
df.to_csv("equilibrio_cinetica.csv", index = False)

In [37]:
df.dtypes

año               int64
convocatoria        str
ejercicio           str
tema                str
tipo_ejercicio      str
dtype: object

In [36]:
df.año = df.año.astype(int)

In [42]:
df.sample(10)

,año,convocatoria,ejercicio,tema,tipo_ejercicio
82,2008,Junio,Ejercicio B4,ácido base,Neutralización ácido-base fuerte (volumen de N...
228,2023,Junio,Ejercicio C3,ácido base,pH ácido débil | Ka | Grado de disociación | D...
172,2017,Reserva 3,Opción B - Ejercicio 3,ácido base,Verdadero/Falso y cuestiones teóricas
146,2014,Septiembre,Opción B - Ejercicio 5,ácido base,"Equilibrio ácido débil (Ka, α, pH) + Kb base c..."
170,2017,Reserva 2,Opción B - Ejercicio 3,ácido base,Hidrólisis de sales (estimación cualitativa de...
198,2020,Reserva 1,Ejercicio C3,ácido base,pH ácido débil | Ka | Kb base conjugada | Conc...
227,2023,Junio,Ejercicio B4,ácido base,Teoría Brønsted-Lowry | pH base débil | Verdad...
199,2020,Reserva 2,Ejercicio C3,ácido base,Disoluciones comerciales | pH base fuerte | Ne...
103,2010,Junio,Opción B - Ejercicio 4,ácido base,Verdadero/Falso y cuestiones teóricas
134,2013,Reserva 3,Opción A - Ejercicio 5,ácido base,Molaridad a partir de densidad/riqueza + Neutr...

In [46]:
df.tipo_ejercicio = df.tipo_ejercicio.apply(lambda x : x.replace("Verdadero/Falso", "Verdadero / Falso"))

In [62]:
df.to_csv("ácido_base.csv", index = False)

In [49]:
df.head()

,año,convocatoria,ejercicio,tema,tipo_ejercicio
0,2000,Junio,Opción A - Ejercicio 4,ácido base,Pares ácido-base conjugados según Brønsted-Low...
1,2000,Junio,Opción B - Ejercicio 6,ácido base,Equilibrio ácido débil: cálculo de masa a part...
2,2000,Reserva 1,Opción A - Ejercicio 3,ácido base,Hidrólisis de sales: color de indicador (estim...
3,2000,Reserva 1,Opción B - Ejercicio 6,ácido base,Equilibrio ácido débil: pH y grado de disociación
4,2000,Reserva 2,Opción A - Ejercicio 3,ácido base,Hidrólisis de NH₄⁺: equilibrio de Brønsted y e...

In [58]:
df["asignatura"] = "química"

In [59]:
df.columns

Index(['año', 'convocatoria', 'ejercicio', 'tema', 'tipo_ejercicio',
       'asignatura'],
      dtype='str')

In [61]:
cols = ["asignatura", "tema", "año", "convocatoria", "ejercicio", "tipo_ejercicio"]
df = df.loc[:, cols]

Insertar datos en la base de datos

In [229]:
csv_files = [f"{i}.csv" for i in ["ácido_base", "equilibrio_cinetica", "redox", "solubilidad"] ]
csv_files

['ácido_base.csv', 'equilibrio_cinetica.csv', 'redox.csv', 'solubilidad.csv']

In [287]:
df = pd.DataFrame()
for csv in csv_files:
    data = pd.read_csv(csv, sep="|")
    df = pd.concat([df, data], axis=0)

In [253]:
df

,asignatura,tema,año,convocatoria,ejercicio,tipo_ejercicio
0,química,ácido base,2000,Junio,"Opción A, Ejercicio 4",Pares ácido-base conjugados según Brønsted-Low...
1,química,ácido base,2000,Junio,"Opción B, Ejercicio 6",Equilibrio ácido débil: cálculo de masa a part...
2,química,ácido base,2000,Reserva 1,"Opción A, Ejercicio 3",Hidrólisis de sales: color de indicador (estim...
3,química,ácido base,2000,Reserva 1,"Opción B, Ejercicio 6",Equilibrio ácido débil: pH y grado de disociación
4,química,ácido base,2000,Reserva 2,"Opción A, Ejercicio 3",Hidrólisis de NH₄⁺: equilibrio de Brønsted y e...
...,...,...,...,...,...,...
129,química,Solubilidad,2011,Septiembre,"Opción A, Ejercicio 6",Ion común numérico
130,química,Solubilidad,2010,Junio,"Opción A, Ejercicio 3",Ks → solubilidad; Influencia del pH
131,química,Solubilidad,2010,Reserva 2,"Opción A, Ejercicio 3",Ks → solubilidad; Efecto ion común teórico
132,química,Solubilidad,2010,Reserva 3,"Opción B, Ejercicio 5",Solubilidad → Ks; Ion común numérico
133,química,Solubilidad,2010,Reserva 4,"Opción A, Ejercicio 6",Solubilidad → Ks; Influencia del pH

In [258]:
df.tema = df.tema.str.lower()

In [289]:
db_df.convocatoria.unique()

<StringArray>
[                 'Junio',              'Reserva 1',              'Reserva 2',
              'Reserva 3',              'Reserva 4',             'Septiembre',
                  'Julio',               'Reserva1',  'Reserva 4 Ejercicio 2',
 'Septiembre Ejercicio 2', 'Septiembre Ejercicio 3',  'Reserva 4 Ejercicio 3']
Length: 12, dtype: str

In [233]:
conn = sqlite3.connect("../database.db")

In [260]:
db_df = pd.read_sql("SELECT * FROM ejercicios", conn)

In [290]:
subset = db_df[db_df.convocatoria.str.contains("Ejercicio")]

In [291]:
subset["ejercicio"] = subset.convocatoria.str.split(" ").apply(
    lambda x : " ".join(x[-2:]) ) + ", " + subset.ejercicio

subset["convocatoria"] = subset.convocatoria.apply(lambda x : " ".join(x.split(" ")[:-2]))

In [293]:
db_df.drop(subset.index, axis=0, inplace = True)

In [294]:
db_df = pd.concat([db_df, subset], axis=0)

In [280]:
subset.convocatoria.str.split(" ").apply(lambda x: " ".join(x[-2:]) )

1388    Ejercicio 2
1389    Ejercicio 2
1415    Ejercicio 2
1416    Ejercicio 2
1421    Ejercicio 2
1422    Ejercicio 2
1432    Ejercicio 2
1447    Ejercicio 2
1448    Ejercicio 2
1453    Ejercicio 2
1454    Ejercicio 3
1465    Ejercicio 2
1466    Ejercicio 2
1487    Ejercicio 3
1488    Ejercicio 2
1497    Ejercicio 2
1498    Ejercicio 2
1503    Ejercicio 3
1509    Ejercicio 2
1510    Ejercicio 2
1515    Ejercicio 2
1521    Ejercicio 2
1536    Ejercicio 2
1551    Ejercicio 2
1552    Ejercicio 2
Name: convocatoria, dtype: str

In [302]:
df.tema.unique()

<StringArray>
['ácido base', 'equilibrio químico', 'cinética', 'redox', 'solubilidad']
Length: 5, dtype: str

In [297]:
db_df.convocatoria = db_df.convocatoria.str.replace("Reserva1", "Reserva 1")

In [ ]:
subset = db_df[db_df.convocatoria.str.contains("Ejercicio")]
for index, row in subset.iterrows():
    conv_ejercicio = " ".join(row["convocatoria"].split(" ")[-2:])
    row["ejercicio"] = f"{row["ejercicio"]}, {conv_ejercicio}"

IndexError: iloc cannot enlarge its target object

In [267]:
subset.convocatoria.unique()

<StringArray>
[ 'Reserva 4 Ejercicio 2', 'Septiembre Ejercicio 2', 'Septiembre Ejercicio 3',
  'Reserva 4 Ejercicio 3']
Length: 4, dtype: str

In [312]:
key_cols = ["asignatura", "tema", "año", "convocatoria", "ejercicio"]

merged = db_df.merge(
    df[key_cols + ["tipo_ejercicio"]],
    on=key_cols,
    how="outer",
    suffixes=("_db", "_new")
)

In [313]:
merged = merged.rename(columns={"tipo_ejercicio_new" : "tipo_ejercicio"})

In [318]:
merged.drop("tipo_ejercicio_db", axis=1, inplace = True)

In [319]:
merged[~merged.tipo_ejercicio.isna()]

,asignatura,tema,año,convocatoria,ejercicio,tipo_ejercicio
145,química,cinética,2000,Reserva 1,"Opción B, Ejercicio 4",Diagrama entálpico / energía de activación
146,química,cinética,2000,Reserva 2,"Opción B, Ejercicio 3",Conceptos teóricos (V/F sobre factores que afe...
147,química,cinética,2001,Junio,"Opción B, Ejercicio 3",Diagrama entálpico / energía de activación / c...
148,química,cinética,2001,Reserva 3,"Opción B, Ejercicio 3",Diagrama entálpico / energía de activación (le...
149,química,cinética,2002,Reserva 3,"Opción B, Ejercicio 3",Diagrama entálpico / energía de activación (le...
...,...,...,...,...,...,...
2317,química,ácido base,2024,Reserva 4,Ejercicio C3,Disoluciones comerciales | pH ácido fuerte | N...
2318,química,ácido base,2025,Junio,Ejercicio 3B,Disoluciones comerciales | pH ácido fuerte | N...
2319,química,ácido base,2025,Reserva 1,Ejercicio 2B,Verdadero / Falso conceptual | Teoría Brønsted...
2320,química,ácido base,2025,Reserva 1,Ejercicio 5,pH ácido débil | Ka | Grado de disociación | D...
2321,química,ácido base,2025,Reserva 2,Ejercicio 3B,pH base débil | Grado de disociación | Kb | pH...

In [323]:
merged[merged.tema.isin(["cinética", "equilibrio químico"])].sort_values(["tema", "año", "convocatoria", "ejercicio"])

,asignatura,tema,año,convocatoria,ejercicio,tipo_ejercicio
145,química,cinética,2000,Reserva 1,"Opción B, Ejercicio 4",Diagrama entálpico / energía de activación
146,química,cinética,2000,Reserva 2,"Opción B, Ejercicio 3",Conceptos teóricos (V/F sobre factores que afe...
147,química,cinética,2001,Junio,"Opción B, Ejercicio 3",Diagrama entálpico / energía de activación / c...
148,química,cinética,2001,Reserva 3,"Opción B, Ejercicio 3",Diagrama entálpico / energía de activación (le...
149,química,cinética,2002,Reserva 3,"Opción B, Ejercicio 3",Diagrama entálpico / energía de activación (le...
...,...,...,...,...,...,...
800,química,equilibrio químico,2025,Junio,"Opción A, Ejercicio 3A",Cálculo de Kc y Kp
801,química,equilibrio químico,2025,Junio,"Opción A, Ejercicio 3A",Cálculo de presiones parciales
802,química,equilibrio químico,2025,Reserva 1,Ejercicio 2A,NaN
803,química,equilibrio químico,2025,Reserva 1,"Opción A, Ejercicio 2A",Principio de Le Chatelier
804,química,equilibrio químico,2025,Reserva 2,Ejercicio 2B,NaN

In [328]:
merged[(merged.tema.isin(["cinética", "equilibrio químico"]))].sort_values(["año", "convocatoria", "ejercicio"])

,asignatura,tema,año,convocatoria,ejercicio,tipo_ejercicio
338,química,equilibrio químico,2000,Junio,"Ejercicio 3, Opción B",NaN
339,química,equilibrio químico,2000,Junio,"Opción B, Ejercicio 3",Conceptos teóricos (endotérmica/exotérmica por...
340,química,equilibrio químico,2000,Reserva 1,"Ejercicio 3, Opción B",NaN
341,química,equilibrio químico,2000,Reserva 1,"Ejercicio 4, Opción B",NaN
342,química,equilibrio químico,2000,Reserva 1,"Ejercicio 5, Opción A",NaN
...,...,...,...,...,...,...
803,química,equilibrio químico,2025,Reserva 1,"Opción A, Ejercicio 2A",Principio de Le Chatelier
804,química,equilibrio químico,2025,Reserva 2,Ejercicio 2B,NaN
198,química,cinética,2025,Reserva 2,"Opción B, Ejercicio 2B",Valor de la constante cinética o velocidad
199,química,cinética,2025,Reserva 2,"Opción B, Ejercicio 2B",Orden de reacción
200,química,cinética,2025,Reserva 2,"Opción B, Ejercicio 2B",Factores que afectan a la velocidad

In [338]:
merged

,asignatura,tema,año,convocatoria,ejercicio,tipo_ejercicio
145,química,cinética,2000,Reserva 1,"Opción B, Ejercicio 4",Diagrama entálpico / energía de activación
146,química,cinética,2000,Reserva 2,"Opción B, Ejercicio 3",Conceptos teóricos (V/F sobre factores que afe...
147,química,cinética,2001,Junio,"Opción B, Ejercicio 3",Diagrama entálpico / energía de activación / c...
148,química,cinética,2001,Reserva 3,"Opción B, Ejercicio 3",Diagrama entálpico / energía de activación (le...
149,química,cinética,2002,Reserva 3,"Opción B, Ejercicio 3",Diagrama entálpico / energía de activación (le...
...,...,...,...,...,...,...
2445,química,átomo,2019,Reserva 2,"Opción B, Ejercicio 2",NaN
2446,química,átomo,2019,Reserva 3,"Opción B, Ejercicio 2",NaN
2447,química,átomo,2019,Reserva 4,"Opción A, Ejercicio 2",NaN
2448,química,átomo,2019,Reserva 4,"Opción B, Ejercicio 2",NaN
2449,química,átomo,2019,Septiembre,"Opción A, Ejercicio 2",NaN

In [339]:
subset = merged[merged.tema.isin(["cinética", "equilibrio químico"])]

In [340]:
subset

,asignatura,tema,año,convocatoria,ejercicio,tipo_ejercicio
145,química,cinética,2000,Reserva 1,"Opción B, Ejercicio 4",Diagrama entálpico / energía de activación
146,química,cinética,2000,Reserva 2,"Opción B, Ejercicio 3",Conceptos teóricos (V/F sobre factores que afe...
147,química,cinética,2001,Junio,"Opción B, Ejercicio 3",Diagrama entálpico / energía de activación / c...
148,química,cinética,2001,Reserva 3,"Opción B, Ejercicio 3",Diagrama entálpico / energía de activación (le...
149,química,cinética,2002,Reserva 3,"Opción B, Ejercicio 3",Diagrama entálpico / energía de activación (le...
...,...,...,...,...,...,...
655,química,equilibrio químico,2019,Reserva 3,"Opción A, Ejercicio 3",NaN
656,química,equilibrio químico,2019,Reserva 3,"Opción B, Ejercicio 5",NaN
658,química,equilibrio químico,2019,Reserva 4,"Opción A, Ejercicio 5",NaN
662,química,equilibrio químico,2019,Septiembre,"Opción A, Ejercicio 3",NaN
663,química,equilibrio químico,2019,Septiembre,"Opción B, Ejercicio 5",NaN

In [344]:
subset.sort_values(["año", "convocatoria", "ejercicio"])[["año", "convocatoria", "ejercicio", "tipo_ejercicio", "tema"]].to_csv("dupli.csv", sep="|", index = False)

In [351]:
merged = merged.sort_values(["año", "convocatoria", "ejercicio", "tipo_ejercicio"]).reset_index(drop = True)

In [357]:
merged = merged.drop_duplicates(subset=["año", "convocatoria", "ejercicio"])

In [361]:
merged

,asignatura,tema,año,convocatoria,ejercicio,tipo_ejercicio
0,química,formulación,2000,Junio,"Opción A, Ejercicio 1",NaN
1,química,cantidad química,2000,Junio,"Opción A, Ejercicio 2",NaN
2,química,enlace químico,2000,Junio,"Opción A, Ejercicio 3",NaN
3,química,ácido base,2000,Junio,"Opción A, Ejercicio 4",Pares ácido-base conjugados según Brønsted-Low...
4,química,cantidad química,2000,Junio,"Opción A, Ejercicio 5",NaN
...,...,...,...,...,...,...
1938,química,reactividad orgánica,2025,Reserva 2,Ejercicio 4B,NaN
1939,química,termoquímica,2025,Reserva 2,Ejercicio 5,NaN
1940,química,cinética,2025,Reserva 2,"Opción B, Ejercicio 2B",Factores que afectan a la velocidad
1941,química,solubilidad,2025,Reserva 3,Ejercicio 3A,NaN
1942,química,solubilidad,2025,Reserva 4,Ejercicio 3B,NaN

In [360]:
merged = merged.sort_values(["año", "convocatoria", "ejercicio"]).reset_index(drop = True)

In [362]:
merged.to_csv("../classifications.csv", sep="|", index = False)